name: 🔨 Build

on: [push]

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 🔨 Build - Windows
            os: windows-latest
            build_artifact_name: screeen.exe
            release_artifact_name: screeen-windows.exe
          - name: 🔨 Build - macOS
            os: macos-latest
            build_artifact_name: screeen
            release_artifact_name: screeen-macos
          - name: 🔨 Build - Linux
            os: ubuntu-latest
            build_artifact_name: screeen
            release_artifact_name: screeen-ubuntu
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install node_modules
        run: yarn install

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.release_artifact_name }}
          path: target/release/${{ matrix.build_artifact_name }}
