name: 🔨 Build

on: [push]

jobs:
  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 🔨 Build - Windows
            os: windows-latest
            artifact_name: screeen.exe
          - name: 🔨 Build - macOS
            os: macos-latest
            artifact_name: screeen
          - name: 🔨 Build - Linux
            os: ubuntu-latest
            artifact_name: screeen
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact_name }}-${{ matrix.os }}
          path: target/release/${{ matrix.artifact_name }}
